# Introducción a Machine Learning con Python #

---

Visual Studio Code y la extensión de Python ofrecen un excelente editor para escenarios de ciencia de datos. Gracias a la compatibilidad nativa con Jupyter Notebooks y Anaconda, es fácil comenzar. En esta sección, usaremos un espacio de trabajo para el tutorial, un entorno de **miniconda** con los módulos de ciencia de datos necesarios para crear un modelo de aprendizaje automático.

## 1. Instalar las librerias necesarias. ##

A fecha de julio de 2025 TensorFlow todavia no está soportado para Python 3.13 por lo que hemos de crear un entorno **conda** con una versión de Python inferior si es que no la tenemos ya. Abrir una **Terminal** de Windows y ejecutar el comando:

`conda create -n cursopython3_12 python=3.12`


Después de crear el entorno nos aseguraremos de **Seleccionar el Kernel** de dicho nuevo entorno y a continuación ejecutaremos el siguiente comando para instalar las librerias necesarias:

NOTA: El símbolo **%** significa que es un comando de terminal.

In [1]:
%conda install numpy pandas jupyter seaborn scikit-learn tensorflow keras

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: c:\Users\Propietario\miniconda3\envs\cursopython3_12

  added / updated specs:
    - jupyter
    - keras
    - numpy
    - pandas
    - scikit-learn
    - seaborn
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libcurl-8.14.1             |       h2300eb9_1         401 KB
    libkrb5-1.21.3             |       hcb72d8e_3         1.2 MB
    libpq-17.4                 |       h4a159e6_2         4.2 MB
    python-3.12.3              |       h1d929f7_0        16.4 MB
    qtbase-6.7.3               |       hd088775_4        20.8 MB
    ------------------------------------------------------------
                                           Total:        43.0 MB

The following NEW packages will be INSTALLED:

  absl-py            pkgs/main/win-64::absl-py-2.1.0-py312haa95532_0
  anyio              pkgs/main/win-64::anyio-4.7.0-py312haa95532_0
  argon2-cffi        pkgs/main/noarch::argon2-cffi-21.3.0-pyhd3eb1b0_0
  argon2-cffi-bindi~ pkgs/main/win-64::argon2-cffi-bindings-21.2.0-py312h827c3e9_1
  astunparse         pkgs/main/noarch::astunparse-1.6.3-py_0
  async-lru          pkgs/main/win-64::async-lru-2.0.4-py312haa95532_0
  attrs              pkgs/main/win-64::attrs-24.3.0-py312haa95532_0
  babel              pkgs/main/win-64::babel-2.16.0-py312haa95532_0
  beautifulsoup4     pkgs/main/win-64::beautifulsoup4-4.13.4-py312haa95532_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  bleach             pkgs/main/win-64::bleach-6.2.0-py312haa95532_0
  bottleneck         pkgs/main/win-64::bottleneck-1.4.2-py312h4b0e54e_0
  brotli-python      pkgs/main/win-64::brotli-python-1.0.9-py312h5da7b33_9
  brotlicffi         pkgs/main/win-64::brotlicffi-1.0.9.2-py312h5da7b33_1
  c-ares             pkgs/main/win-64::c-ares-1.19.1-h2bbff1b_0
  certifi            pkgs/main/win-64::certifi-2025.7.14-py312haa95532_0
  cffi               pkgs/main/win-64::cffi-1.17.1-py312h827c3e9_1
  charset-normalizer pkgs/main/noarch::charset-normalizer-3.3.2-pyhd3eb1b0_0
  contourpy          pkgs/main/win-64::contourpy-1.3.1-py312h214f63a_0
  cycler             pkgs/main/noarch::cycler-0.11.0-pyhd3eb1b0_0
  defusedxml         pkgs/main/noarch::defusedxml-0.7.1-pyhd3eb1b0_0
  fonttools          pkgs/main/win-64::fonttools-4.55.3-py312h827c3e9_0
  freetype           pkgs/main/win-64::freetype-2.13.3-h0620614_0
  gast               pkgs/main/noarch::gast-0.6.0-pyhd3eb1b0_0
  giflib             pkgs/main/win-64::giflib-5.2.2-h7edc060_0
  google-pasta       pkgs/main/noarch::google-pasta-0.2.0-pyhd3eb1b0_0
  grpcio             pkgs/main/win-64::grpcio-1.71.0-py312hbb1fe6b_0
  h11                pkgs/main/win-64::h11-0.16.0-py312haa95532_0
  h5py               pkgs/main/win-64::h5py-3.14.0-py312h6fc9867_0
  hdf5               pkgs/main/win-64::hdf5-1.14.5-ha36df97_2
  httpcore           pkgs/main/win-64::httpcore-1.0.9-py312haa95532_0
  httpx              pkgs/main/win-64::httpx-0.28.1-py312haa95532_0
  icc_rt             pkgs/main/win-64::icc_rt-2022.1.0-h6049295_2
  icu                pkgs/main/win-64::icu-73.1-h6c2663c_0
  idna               pkgs/main/win-64::idna-3.7-py312haa95532_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2023.1.0-h59b6b97_46320
  ipywidgets         pkgs/main/win-64::ipywidgets-8.1.5-py312haa95532_0
  jinja2             pkgs/main/win-64::jinja2-3.1.6-py312haa95532_0
  joblib             pkgs/main/win-64::joblib-1.4.2-py312haa95532_0
  jpeg               pkgs/main/win-64::jpeg-9e-h827c3e9_3
  json5              pkgs/main/win-64::json5-0.9.25-py312haa95532_0
  jsonschema         pkgs/main/win-64::jsonschema-4.25.0-py312haa95532_0
  jsonschema-specif~ pkgs/main/win-64::jsonschema-specifications-2023.7.1-py312haa95532_0
  jupyter            pkgs/main/win-64::jupyter-1.1.1-py312haa95532_0
  jupyter-lsp        pkgs/main/win-64::jupyter-lsp-2.2.5-py312haa95532_0
  jupyter_console    pkgs/main/win-64::jupyter_console-6.6.3-py312haa95532_1
  jupyter_events     pkgs/main/win-64::jupyter_events-0.12.0-py312haa95532_0
  jupyter_server     pkgs/main/win-64::jupyter_server-2.16.0-py312haa95532_0
  jupyter_server_te~ pkgs/main/win-64::jupyter_server_terminals-0.5.3-py312haa95532_0
  jupyterlab         pkgs/main/win-64::jupyterlab-4.4.4-py312haa95532_0
  jupyterlab_pygmen~ pkgs/main/win-64::jupyterlab_pygments-0.3.0-py312haa95532_0
  jupyterlab_server  pkgs/main/win-64::jupyterlab_server-2.27.3-py312haa95532_0
  jupyterlab_widgets pkgs/main/win-64::jupyterlab_widgets-3.0.15-py312haa95532_0
  keras              pkgs/main/win-64::keras-3.6.0-py312haa95532_0
  kiwisolver         pkgs/main/win-64::kiwisolver-1.4.8-py312h5da7b33_0
  lcms2              pkgs/main/win-64::lcms2-2.16-hb4a4139_0
  lerc               pkgs/main/win-64::lerc-3.0-hd77b12b_0
  libabseil          pkgs/main/win-64::libabseil-20250127.0-cxx17_h52369b4_0
  libcurl            pkgs/main/win-64::libcurl-8.14.1-h2300eb9_1
  libdeflate         pkgs/main/win-64::libdeflate-1.17-h2bbff1b_1
  libgrpc            pkgs/main/win-64::libgrpc-1.71.0-hf4237ab_0
  libkrb5            pkgs/main/win-64::libkrb5-1.21.3-hcb72d8e_3
  libpng             pkgs/main/win-64::libpng-1.6.39-h8cc25b3_0
  libpq              pkgs/main/win-64::libpq-17.4-h4a159e6_2
  libprotobuf        pkgs/main/win-64::libprotobuf-5.29.3-h65a231f_1
  libre2-11          pkgs/main/win-64::libre2-11-2024.07.02-h5da7b33_0
  libssh2            pkgs/main/win-64::libssh2-1.11.1-h2addb87_0
  libtiff            pkgs/main/win-64::libtiff-4.5.1-hd77b12b_0
  libwebp-base       pkgs/main/win-64::libwebp-base-1.3.2-h3d04722_1
  lz4-c              pkgs/main/win-64::lz4-c-1.9.4-h2bbff1b_1
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markdown           pkgs/main/win-64::markdown-3.8-py312haa95532_0
  markdown-it-py     pkgs/main/win-64::markdown-it-py-2.2.0-py312haa95532_1
  markupsafe         pkgs/main/win-64::markupsafe-3.0.2-py312h827c3e9_0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.10.0-py312he19b0ae_0
  mdurl              pkgs/main/win-64::mdurl-0.1.0-py312haa95532_0
  mistune            pkgs/main/win-64::mistune-3.1.2-py312haa95532_0
  mkl                pkgs/main/win-64::mkl-2023.1.0-h6b88ed4_46358
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py312h827c3e9_2
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.11-py312h827c3e9_0
  mkl_random         pkgs/main/win-64::mkl_random-1.2.8-py312h0158946_0
  ml_dtypes          pkgs/main/win-64::ml_dtypes-0.5.1-py312h094160a_0
  mpi                pkgs/main/win-64::mpi-1.0-msmpi
  mpi4py             pkgs/main/win-64::mpi4py-4.0.3-py312h827c3e9_0
  msmpi              pkgs/main/win-64::msmpi-10.1.1-had4844c_0
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  namex              pkgs/main/win-64::namex-0.0.7-py312haa95532_0
  nbclient           pkgs/main/win-64::nbclient-0.10.2-py312haa95532_0
  nbconvert          pkgs/main/win-64::nbconvert-7.16.6-py312haa95532_0
  nbconvert-core     pkgs/main/win-64::nbconvert-core-7.16.6-py312haa95532_0
  nbconvert-pandoc   pkgs/main/win-64::nbconvert-pandoc-7.16.6-py312haa95532_0
  nbformat           pkgs/main/win-64::nbformat-5.10.4-py312haa95532_0
  notebook           pkgs/main/win-64::notebook-7.4.4-py312haa95532_0
  notebook-shim      pkgs/main/win-64::notebook-shim-0.2.4-py312haa95532_0
  numexpr            pkgs/main/win-64::numexpr-2.11.0-py312hdb065b2_0
  numpy              pkgs/main/win-64::numpy-2.0.2-py312hfd52020_0
  numpy-base         pkgs/main/win-64::numpy-base-2.0.2-py312h4dde369_0
  openjpeg           pkgs/main/win-64::openjpeg-2.5.2-hae555c5_0
  opt_einsum         pkgs/main/noarch::opt_einsum-3.3.0-pyhd3eb1b0_1
  optree             pkgs/main/win-64::optree-0.14.1-py312h214f63a_0
  overrides          pkgs/main/win-64::overrides-7.4.0-py312haa95532_0
  pandas             pkgs/main/win-64::pandas-2.3.1-py312h885b0b7_0
  pandoc             pkgs/main/win-64::pandoc-2.12-haa95532_3
  pandocfilters      pkgs/main/noarch::pandocfilters-1.5.0-pyhd3eb1b0_0
  pillow             pkgs/main/win-64::pillow-11.1.0-py312h096bfcc_0
  prometheus_client  pkgs/main/win-64::prometheus_client-0.21.1-py312haa95532_0
  prompt_toolkit     pkgs/main/noarch::prompt_toolkit-3.0.43-hd3eb1b0_0
  protobuf           pkgs/main/win-64::protobuf-5.29.3-py312h5da7b33_0
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pyparsing          pkgs/main/win-64::pyparsing-3.2.0-py312haa95532_0
  pyqt               pkgs/main/win-64::pyqt-6.7.1-py312h378bd72_2
  pyqt6-sip          pkgs/main/win-64::pyqt6-sip-13.9.1-py312h02ab6af_2
  pysocks            pkgs/main/win-64::pysocks-1.7.1-py312haa95532_0
  python-fastjsonsc~ pkgs/main/win-64::python-fastjsonschema-2.20.0-py312haa95532_0
  python-flatbuffers pkgs/main/win-64::python-flatbuffers-24.3.25-py312haa95532_0
  python-json-logger pkgs/main/win-64::python-json-logger-3.2.1-py312haa95532_0
  python-tzdata      pkgs/main/noarch::python-tzdata-2025.2-pyhd3eb1b0_0
  pytz               pkgs/main/win-64::pytz-2025.2-py312haa95532_0
  pywinpty           pkgs/main/win-64::pywinpty-2.0.15-py312h72d21ff_0
  pyyaml             pkgs/main/win-64::pyyaml-6.0.2-py312h827c3e9_0
  qtbase             pkgs/main/win-64::qtbase-6.7.3-hd088775_4
  qtconsole          pkgs/main/win-64::qtconsole-5.6.1-py312haa95532_1
  qtdeclarative      pkgs/main/win-64::qtdeclarative-6.7.3-h885b0b7_1
  qtpy               pkgs/main/win-64::qtpy-2.4.1-py312haa95532_0
  qtsvg              pkgs/main/win-64::qtsvg-6.7.3-h9d4b640_1
  qttools            pkgs/main/win-64::qttools-6.7.3-hcb596f7_1
  qtwebchannel       pkgs/main/win-64::qtwebchannel-6.7.3-h885b0b7_1
  qtwebsockets       pkgs/main/win-64::qtwebsockets-6.7.3-h885b0b7_1
  re2                pkgs/main/win-64::re2-2024.07.02-h214f63a_0
  referencing        pkgs/main/win-64::referencing-0.30.2-py312haa95532_0
  requests           pkgs/main/win-64::requests-2.32.4-py312haa95532_0
  rfc3339-validator  pkgs/main/win-64::rfc3339-validator-0.1.4-py312haa95532_0
  rfc3986-validator  pkgs/main/win-64::rfc3986-validator-0.1.1-py312haa95532_0
  rich               pkgs/main/win-64::rich-13.9.4-py312haa95532_0
  rpds-py            pkgs/main/win-64::rpds-py-0.22.3-py312h636fa0f_0
  scikit-learn       pkgs/main/win-64::scikit-learn-1.7.1-py312h3fbe716_0
  scipy              pkgs/main/win-64::scipy-1.16.0-py312h242c13b_0
  seaborn            pkgs/main/win-64::seaborn-0.13.2-py312haa95532_3
  send2trash         pkgs/main/win-64::send2trash-1.8.2-py312haa95532_1
  sip                pkgs/main/win-64::sip-6.10.0-py312h5da7b33_0
  snappy             pkgs/main/win-64::snappy-1.2.1-hcdb6601_0
  sniffio            pkgs/main/win-64::sniffio-1.3.0-py312haa95532_0
  soupsieve          pkgs/main/win-64::soupsieve-2.5-py312haa95532_0
  tbb                pkgs/main/win-64::tbb-2021.8.0-h59b6b97_0
  tensorboard        pkgs/main/win-64::tensorboard-2.18.0-py312haa95532_0
  tensorboard-data-~ pkgs/main/win-64::tensorboard-data-server-0.7.0-py312haa95532_1
  tensorflow         pkgs/main/win-64::tensorflow-2.18.1-cpu_py312h6605a60_0
  tensorflow-base    pkgs/main/win-64::tensorflow-base-2.18.1-cpu_py312h1ab519a_0
  termcolor          pkgs/main/win-64::termcolor-2.1.0-py312haa95532_0
  terminado          pkgs/main/win-64::terminado-0.17.1-py312haa95532_0
  threadpoolctl      pkgs/main/win-64::threadpoolctl-3.5.0-py312hfc267ef_0
  tinycss2           pkgs/main/win-64::tinycss2-1.4.0-py312haa95532_0
  typing-extensions  pkgs/main/win-64::typing-extensions-4.12.2-py312haa95532_0
  unicodedata2       pkgs/main/win-64::unicodedata2-15.1.0-py312h827c3e9_1
  urllib3            pkgs/main/win-64::urllib3-2.5.0-py312haa95532_0
  webencodings       pkgs/main/win-64::webencodings-0.5.1-py312haa95532_2
  websocket-client   pkgs/main/win-64::websocket-client-1.8.0-py312haa95532_0
  werkzeug           pkgs/main/win-64::werkzeug-3.1.3-py312haa95532_0
  widgetsnbextension pkgs/main/win-64::widgetsnbextension-4.0.13-py312haa95532_0
  win_inet_pton      pkgs/main/win-64::win_inet_pton-1.1.0-py312haa95532_0
  winpty             pkgs/main/win-64::winpty-0.4.3-4
  wrapt              pkgs/main/win-64::wrapt-1.17.0-py312h827c3e9_0
  yaml               pkgs/main/win-64::yaml-0.2.5-he774522_0
  zstd               pkgs/main/win-64::zstd-1.5.6-h8880b57_0

The following packages will be REMOVED:

  cpython-3.12.11-py312hd8ed1ab_0
  libzlib-1.3.1-h2466b09_2
  python_abi-3.12-8_cp312

The following packages will be SUPERSEDED by a higher-priority channel:

  debugpy            conda-forge::debugpy-1.8.15-py312ha1a~ --> pkgs/main::debugpy-1.8.11-py312h5da7b33_0
  jupyter_core       conda-forge/noarch::jupyter_core-5.8.~ --> pkgs/main/win-64::jupyter_core-5.8.1-py312haa95532_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.~ --> pkgs/main/win-64::prompt-toolkit-3.0.43-py312haa95532_0
  psutil             conda-forge::psutil-7.0.0-py312h4389b~ --> pkgs/main::psutil-5.9.0-py312h827c3e9_1
  python             conda-forge::python-3.12.11-h3f84c4b_~ --> pkgs/main::python-3.12.3-h1d929f7_0
  pywin32            conda-forge::pywin32-311-py312h829343~ --> pkgs/main::pywin32-308-py312h5da7b33_0
  pyzmq              conda-forge::pyzmq-27.0.0-py312hd7027~ --> pkgs/main::pyzmq-26.2.0-py312h5da7b33_0
  setuptools         conda-forge/noarch::setuptools-80.9.0~ --> pkgs/main/win-64::setuptools-72.1.0-py312haa95532_0
  tornado            conda-forge::tornado-6.5.1-py312h4389~ --> pkgs/main::tornado-6.5.1-py312h827c3e9_0
  typing_extensions  conda-forge/noarch::typing_extensions~ --> pkgs/main/win-64::typing_extensions-4.12.2-py312haa95532_0
  zlib                   conda-forge::zlib-1.3.1-h2466b09_2 --> pkgs/main::zlib-1.2.13-h8cc25b3_1



Downloading and Extracting Packages: ...working...
qtbase-6.7.3         | 20.8 MB   |            |   0%

python-3.12.3        | 16.4 MB   |            |   0%


libpq-17.4           | 4.2 MB    |            |   0%



libkrb5-1.21.3       | 1.2 MB    |            |   0%




libcurl-8.14.1       | 401 KB    |            |   0%
qtbase-6.7.3         | 20.8 MB   |            |   0%

python-3.12.3        | 16.4 MB   |            |   0%




libcurl-8.14.1       | 401 KB    | 3          |   4%



libkrb5-1.21.3       | 1.2 MB    | 1          |   1%


libpq-17.4           | 4.2 MB    |            |   0%
qtbase-6.7.3         | 20.8 MB   | 6          |   6%

python-3.12.3        | 16.4 MB   | 1          |   2%



libkrb5-1.21.3       | 1.2 MB    | ##1        |  21%


libpq-17.4           | 4.2 MB    | 5          |   6%




libcurl-8.14.1       | 401 KB    | ######3    |  64%




libcurl-8.14.1       | 401 KB    | ########## | 100%
qtbase-6.7.3         | 20.8 MB   | #6         |  16%

python-3.12.3        | 16.4 MB   | 5          |   6%




libcurl-8.14.1       | 401 KB    | ########## | 100%




libcurl-8.14.1       | 401 KB    | ########## | 100%



libkrb5-1.21.3       | 1.2 MB    | ######     |  61%


libpq-17.4           | 4.2 MB    | 9          |   9%
qtbase-6.7.3         | 20.8 MB   | ##2        |  23%

python-3.12.3        | 16.4 MB   | 7          |   8%



libkrb5-1.21.3       | 1.2 MB    | ########## | 100%


libpq-17.4           | 4.2 MB    | #7         |  17%
qtbase-6.7.3         | 20.8 MB   | ###        |  30%

python-3.12.3        | 16.4 MB   | #3         |  14%


libpq-17.4           | 4.2 MB    | ##6        |  26%
qtbase-6.7.3         | 20.8 MB   | ###7       |  37%

python-3.12.3        | 16.4 MB   | #9         |  19%


libpq-17.4           | 4.2 MB    | ###6       |  36%
qtbase-6.7.3         | 20.8 MB   | ####3      |  44%

python-3.12.3        | 16.4 MB   | ##6        |  26%


libpq-17.4           | 4.2 MB    | #####      |  51%
qtbase-6.7.3         | 20.8 MB   | #####      |  51%

python-3.12.3        | 16.4 MB   | ###2       |  32%
qtbase-6.7.3         | 20.8 MB   | #####7     |  57%


libpq-17.4           | 4.2 MB    | ######3    |  64%

python-3.12.3        | 16.4 MB   | ###9       |  39%


libpq-17.4           | 4.2 MB    | #######6   |  77%



libkrb5-1.21.3       | 1.2 MB    | ########## | 100%
qtbase-6.7.3         | 20.8 MB   | ######3    |  64%



libkrb5-1.21.3       | 1.2 MB    | ########## | 100%

python-3.12.3        | 16.4 MB   | ####5      |  46%
qtbase-6.7.3         | 20.8 MB   | #######1   |  72%


libpq-17.4           | 4.2 MB    | ########8  |  88%

python-3.12.3        | 16.4 MB   | #####1     |  52%
qtbase-6.7.3         | 20.8 MB   | #######8   |  79%

python-3.12.3        | 16.4 MB   | #####9     |  59%


libpq-17.4           | 4.2 MB    | ########## | 100%


libpq-17.4           | 4.2 MB    | ########## | 100%
qtbase-6.7.3         | 20.8 MB   | ########6  |  87%

python-3.12.3        | 16.4 MB   | ######7    |  68%
qtbase-6.7.3         | 20.8 MB   | #########4 |  94%

python-3.12.3        | 16.4 MB   | #######4   |  75%

python-3.12.3        | 16.4 MB   | ########5  |  85%

python-3.12.3        | 16.4 MB   | #########3 |  93%
qtbase-6.7.3         | 20.8 MB   | ########## | 100%

python-3.12.3        | 16.4 MB   | ########## | 100%
qtbase-6.7.3         | 20.8 MB   | ########## | 100%


libpq-17.4           | 4.2 MB    | ########## | 100%

python-3.12.3        | 16.4 MB   | ########## | 100%















                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

C:\Users\Propietario\miniconda3\Lib\site-packages\menuinst\platforms\win.py:69: UserWarning: Quick launch menus are not available for system level installs
  warnings.warn("Quick launch menus are not available for system level installs")
Overwriting existing link at C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda (miniconda3)\Jupyter Notebook (cursopython3_12).lnk.

Terminal profiles are not available for system level installs

Si prefieres ejecutar el comando anterior desde la **Terminal** integrada de __VS Code__, abre la terminal desde el menú __Ver->Terminal__ y ejecuta el comando asegurándote de que activas el entorno ejecutando primero:

`conda activate cursopython3_12`

## 2. Importar los datos. ##

Vamos a utilizar el fichero **titanic3.csv**

In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv('titanic3.csv')
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

Ahora visualizaremos algunas estadísticas

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('default')  # Cambiar a 'dark_background' si se prefiere un fondo oscuro
fig, axs = plt.subplots(ncols=5, figsize=(30,5))
sns.violinplot(x="survived", y="age", hue="sex", data=data, ax=axs[0])
sns.pointplot(x="sibsp", y="survived", hue="sex", data=data, ax=axs[1])
sns.pointplot(x="parch", y="survived", hue="sex", data=data, ax=axs[2])
sns.pointplot(x="pclass", y="survived", hue="sex", data=data, ax=axs[3])
sns.violinplot(x="survived", y="fare", hue="sex", data=data, ax=axs[4])

Estos gráficos son útiles para visualizar algunas de las relaciones entre la supervivencia y las variables de entrada de los datos, pero también es posible usar **pandas** para calcular correlaciones. Para ello, todas las variables utilizadas deben ser numéricas para el cálculo de la correlación, y actualmente el género se almacena como una cadena. Para convertir esos valores de cadena a enteros, agregue y ejecute el siguiente código:

In [3]:
data.replace({'male': 1, 'female': 0}, inplace=True)

C:\Users\Propietario\AppData\Local\Temp\ipykernel_15536\761646214.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'male': 1, 'female': 0}, inplace=True)

Ahora, puede analizar la correlación entre todas las variables de entrada para identificar las características que serían las mejores entradas para un modelo de aprendizaje automático. Cuanto más cercano esté un valor a 1, mayor será la correlación entre el valor y el resultado. Utilice el siguiente código para correlacionar la relación entre todas las variables y la supervivencia.

In [4]:
data.corr(numeric_only=True).abs()[["survived"]]

          survived
pclass    0.312469
survived  1.000000
sex       0.528693
age       0.055512
sibsp     0.027825
parch     0.082660
fare      0.244265
body           NaN

Al observar los resultados de la correlación, notará que algunas variables, como el género, tienen una correlación bastante alta con la supervivencia, mientras que otras, como los parientes (sibsp = hermanos o cónyuge, parch = padres o hijos), parecen tener poca correlación.

Supongamos que sibsp y parch están relacionados en cuanto a su efecto sobre la supervivencia, y agrupémoslos en una nueva columna llamada "parientes" para ver si su combinación tiene una mayor correlación con la supervivencia. Para ello, comprobaremos si, para un pasajero dado, el número de sibsp y parch es mayor que 0 y, de ser así, podemos afirmar que tenía un familiar a bordo.

Utilice el siguiente código para crear una nueva variable y columna en el conjunto de datos llamado relativesy verificar la correlación nuevamente.

In [5]:
data['relatives'] = data.apply (lambda row: int((row['sibsp'] + row['parch']) > 0), axis=1)
data.corr(numeric_only=True).abs()[["survived"]]

           survived
pclass     0.312469
survived   1.000000
sex        0.528693
age        0.055512
sibsp      0.027825
parch      0.082660
fare       0.244265
body            NaN
relatives  0.201719

Observará que, de hecho, al analizar si una persona tenía parientes, en comparación con cuántos, existe una mayor correlación con la supervivencia. Con esta información, puede eliminar del conjunto de datos las columnas sibsp y parch de bajo valor , así como las filas con valores NaN , para obtener un conjunto de datos que pueda usarse para entrenar un modelo.

Aunque la edad tenía una correlación directa baja, se mantuvo porque parece razonable que aún pudiera tener correlación junto con otras entradas.

In [6]:
data = data[['sex', 'pclass','age','relatives','fare','survived']].dropna()

## 3. Entrenar y Evaluar un Modelo. ##

Con el conjunto de datos listo, podemos empezar a crear un modelo. En esta sección, usaremos la biblioteca **scikit-learn** (ya que ofrece funciones auxiliares útiles) para preprocesar el conjunto de datos, entrenar un modelo de clasificación para determinar la supervivencia del Titanic y, a continuación, usar ese modelo con datos de prueba para determinar su precisión.

Un primer paso común para entrenar un modelo es dividir el conjunto de datos en datos de entrenamiento y de validación. Esto permite usar una parte de los datos para entrenar el modelo y otra para probarlo. Si se usaran todos los datos para entrenar el modelo, no habría forma de estimar su rendimiento real con datos que el modelo aún no ha analizado. Una ventaja de la biblioteca **scikit-learn** es que proporciona un método específico para dividir un conjunto de datos en datos de entrenamiento y de prueba.

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data[['sex','pclass','age','relatives','fare']], data.survived, test_size=0.2, random_state=0)

A continuación, normalizaremos las entradas para que todas las características se traten por igual. Por ejemplo, dentro del conjunto de datos, los valores de edad oscilan entre ~0 y 100, mientras que el género solo es 1 o 0. Al normalizar todas las variables, puede garantizar que los rangos de valores sean iguales. Utilice el siguiente código para escalar los valores de entrada.

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

Existen muchos algoritmos de aprendizaje automático diferentes para modelar los datos. La biblioteca scikit-learn también ofrece compatibilidad con muchos de ellos y una tabla para ayudarte a seleccionar el más adecuado para tu situación. Por ahora, utiliza el algoritmo Naïve Bayes , un algoritmo común para problemas de clasificación. Agrega una celda con el siguiente código para crear y entrenar el algoritmo.

In [9]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

Con un modelo entrenado, ahora podemos probarlo con el conjunto de datos de prueba que no se entrenó. Ejecutaremos el siguiente código para predecir el resultado de los datos de prueba y calcular la precisión del modelo.

In [10]:
from sklearn import metrics

predict_test = model.predict(X_test)
print(metrics.accuracy_score(y_test, predict_test))

prediction = model.predict(sc.transform([[0, 1, 22, 0, 7.25]]))  # Ejemplo de predicción
print("Predicción para un pasajero femenino de clase 1, 22 años, sin familiares a bordo y tarifa 7.25:", "Sobrevivió" if prediction[0] == 1 else "No sobrevivió")

0.7464114832535885
Predicción para un pasajero femenino de clase 1, 22 años, sin familiares a bordo y tarifa 7.25: Sobrevivió

c:\Users\Propietario\miniconda3\envs\cursopython3_12\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## 4. Utilizar una Red Neuronal ##

Una red neuronal es un modelo que utiliza ponderaciones y funciones de activación, modelando aspectos de las neuronas humanas, para determinar un resultado basado en las entradas proporcionadas. A diferencia del algoritmo de aprendizaje automático que se analizó anteriormente, las redes neuronales son una forma de aprendizaje profundo en la que no es necesario conocer de antemano un algoritmo ideal para el conjunto de problemas. Se puede utilizar en diversos escenarios, y la clasificación es uno de ellos. En esta sección, se utilizará la biblioteca Keras con TensorFlow para construir la red neuronal y explorar cómo gestiona el conjunto de datos del Titanic.

In [12]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

Tras definir el modelo, el siguiente paso es añadir las capas de la red neuronal. Por ahora, simplifiquemos el proceso y usemos solo tres capas.

In [13]:
model.add(Dense(5, kernel_initializer = 'uniform', activation = 'relu', input_dim = 5))
model.add(Dense(5, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))

c:\Users\Propietario\miniconda3\envs\cursopython3_12\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

La primera capa se configurará para que tenga una dimensión de 5, ya que tiene cinco entradas: sexo, clase, edad, parientes y tarifa.

La última capa debe generar 1, ya que se desea una salida unidimensional que indique si un pasajero sobreviviría.

La capa intermedia se mantuvo en 5 para simplificar, aunque ese valor podría haber sido diferente.

La función de activación de la unidad lineal rectificada (relu) se utiliza como una buena función de activación general para las primeras dos capas, mientras que la función de activación sigmoidea es necesaria para la capa final, ya que el resultado deseado (si un pasajero sobrevive o no) debe escalarse en el rango de 0 a 1 (la probabilidad de que un pasajero sobreviva).

PAra ver un resumen del modelo:

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 66 (264.00 B)

 Trainable params: 66 (264.00 B)

 Non-trainable params: 0 (0.00 B)

Una vez creado el modelo, es necesario compilarlo. Para ello, es necesario definir el tipo de optimizador que se utilizará, cómo se calculará la pérdida y qué métrica se optimizará. Agregue el siguiente código para compilar y entrenar el modelo.

In [15]:
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.4952 - loss: 0.6931
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6011 - loss: 0.6913
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6012 - loss: 0.6893
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5731 - loss: 0.6883
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5959 - loss: 0.6840
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6419 - loss: 0.6795
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7403 - loss: 0.6729
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7599 - loss: 0.6622
Epoch 9/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7477 - loss: 0.6491
Epoch 10/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7648 - loss: 0.6300
Epoch 11/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7527 - loss: 0.6022
Epoch 12/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7621 - loss: 0.5805
Epoch 13/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7566 - loss: 0.5548
Epoch 14/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7652 - loss: 0.5282
Epoch 15/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7882 - loss: 0.4951
Epoch 16/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7940 - loss: 0.4692
Epoch 17/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7979 - loss: 0.4632
Epoch 18/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7689 - loss: 0.4793
Epoch 19/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7906 - loss: 0.4571
Epoch 20/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7804 - loss: 0.4578
Epoch 21/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4540
Epoch 22/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7726 - loss: 0.4778
Epoch 23/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7756 - loss: 0.4767
Epoch 24/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7803 - loss: 0.4508
Epoch 25/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7918 - loss: 0.4528
Epoch 26/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7991 - loss: 0.4402
Epoch 27/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7858 - loss: 0.4399
Epoch 28/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7841 - loss: 0.4426
Epoch 29/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7939 - loss: 0.4374
Epoch 30/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7867 - loss: 0.4347
Epoch 31/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7906 - loss: 0.4476
Epoch 32/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7946 - loss: 0.4312
Epoch 33/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7810 - loss: 0.4732
Epoch 34/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7662 - loss: 0.4926
Epoch 35/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7910 - loss: 0.4494
Epoch 36/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7975 - loss: 0.4484
Epoch 37/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7809 - loss: 0.4453
Epoch 38/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8003 - loss: 0.4382
Epoch 39/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8018 - loss: 0.4324
Epoch 40/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7867 - loss: 0.4391
Epoch 41/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7767 - loss: 0.4433
Epoch 42/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8099 - loss: 0.4274
Epoch 43/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7990 - loss: 0.4410
Epoch 44/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7901 - loss: 0.4613
Epoch 45/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4427
Epoch 46/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4326
Epoch 47/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7803 - loss: 0.4501
Epoch 48/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7694 - loss: 0.4779
Epoch 49/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7980 - loss: 0.4440
Epoch 50/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7919 - loss: 0.4480

Ahora que el modelo está construido y entrenado, podemos ver cómo funciona con los datos de prueba.

In [16]:
y_pred = np.rint(model.predict(X_test).flatten())
print(metrics.accuracy_score(y_test, y_pred))

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
0.7942583732057417

Con esta sencilla red neuronal, el resultado es mejor que el 75 % de precisión del clasificador Naive Bayes probado anteriormente.

Si lo que queremos es calcular un resultado nuevo, podemos hacer lo siguiente:

In [20]:
My_Test= np.array([[0, 1, 22, 0, 7.25]])
My_Test = sc.transform(My_Test)

y_pred = np.rint(model.predict(My_Test).flatten())
print("Probabilidad de supervivencia:", y_pred[0])

c:\Users\Propietario\miniconda3\envs\cursopython3_12\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
Probabilidad de supervivencia: 1.0